spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.104.25.139:3306/bms?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: hpdihpdi
  rabbitmq:
        host: 192.168.198.131
        port: 5672
        username: guest
        password: guest
  jpa:
    show-sql: true
server:
  port: 8082

env:
  order
